-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 13 فبراير 2023 الساعة 06:45
-- إصدار الخادم: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bot`
--

-- --------------------------------------------------------

--
-- بنية الجدول `chatbot`
--

CREATE TABLE `chatbot` (
  `id` int(11) NOT NULL,
  `queries` varchar(2000) NOT NULL,
  `replies` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- إرجاع أو استيراد بيانات الجدول `chatbot`
--

INSERT INTO `chatbot` (`id`, `queries`, `replies`) VALUES
(1, 'info | information| Information | INFORMATION|INFO', 'Please select the disease that you would like to know about.<br/>\r\n1•Cataract.<br/>\r\n2•Glaucoma.<br/>\r\n3•Dry eye.<br/>\r\n4•Keratoconus.<br/>\r\n5•Keratitis.<br/>\r\n6•retinal detachment.<br/>\r\n\r\n'),
(2, 'Cataract | cataract |CATARACT|1', 'Please choose what you want.</br>\r\n<b>Cataract Symptoms</b> <br/>\r\n<b>Cataract Risk factors</b> <br/>\r\n<b>Cataract Diagnosis</b> <br/>\r\n<b>Cataract Treatment</b> <br/>\r\n<b>Cataract Protection</b> <br/>'),
(3, 'cataract symptoms |Cataract Symptoms |CATARACT SYMPTOMS\r\n', '<b> Cataract Symptoms: </b>\r\n<br/>\r\n•Gradual visual impairment without pain.<br/>\r\n•Frequent change of glasses or contact lenses.<br/>\r\n•The color of the lens of the eye gradually changes to white or brown in advanced cases.<br/>\r\n•Blurry vision (fog).<br/>\r\n•Sensitivity to lights.<br/>\r\n•Difficulty seeing at night.<br/>\r\n•Seeing halos around light sources.<br/>\r\n•Yellowing of colors.<br/>\r\n•Difficulty reading and distinguishing faces.<br/>\r\n\r\n'),
(4, 'Cataract Risk factors |cataract risk factors |CATARACT RISK FACTORS |cataract risk factor |CATARACT RISK FACTOR |Cataract Risk factor', '<b> Cataract Risk factors </b> <br/>\r\n•Getting old.<br/>\r\n•Exposure to sunlight (UV rays).<br/>\r\n•Exposure to a blow or injury to the eye.<br/>\r\n•Having diabetes.<br/>\r\n•Having high blood pressure.<br/>\r\n•Some medicines, the most important of which is cortisone.<br/>\r\n•Prior exposure to blind eyes.<br/>\r\n•Smoking.<br/>\r\n'),
(5, 'cataract diagnosis |CATARACT DIAGNOSIS| Cataract Diagnosis', '<b>Cataract Diagnosis: </b> </br>\r\n1.Clinical examination.<br/>\r\n2.Medical history.<br/>\r\nundergo some tests<br/>\r\n1.Visual acuity measurement.<br/>\r\n2.Evaluation of the lens and retina of the eye.<br/>\r\n3.Intraocular pressure measurement.<br/>\r\n4.Fundoscopy.<br/>\r\n5.seeing a red light reflection; As its absence means the presence of opacity.<br/>\r\n'),
(6, 'Cataract Treatment |cataract treatment |CATARACT TREATMENT', '<b> Cataract Treatment</b> </br>\r\nThe only treatment for it is surgical intervention.<br/>\r\n  One of the most important surgical interventions is the removal of the lens affected by the cataract and replacing it with the implantation of another new lens that lasts a lifetime. This process has different methods in different cases.\r\n'),
(7, 'CATARACT PROTECTION |Cataract Protection |cataract protection', '<b> Cataract Treatment</b> </br>\r\n•Have regular eye exams.<br/>\r\n•Quit Smoking.<br/>\r\n•Follow the treatment plan for health problems such as: diabetes, and others.<br/>\r\n•Choose a healthy diet that contains vitamins and antioxidants.<br/>\r\n•Wear sunglasses that block ultraviolet rays.\r\n'),
(9, 'glaucoma | Glaucoma | GLAUCOMA|2', 'Please choose what you want.</br>\r\n<b>Glaucoma Symptoms</b> <br/>\r\n<b>Glaucoma Risk factors</b> <br/>\r\n<b>Glaucoma Diagnosis</b> <br/>\r\n<b>Glaucoma Treatment</b> <br/>\r\n<b>Glaucoma Protection</b> <br/>'),
(10, 'glaucoma symptoms |Glaucoma Symptoms |GLAUCOMA SYMPTOMS', '<b> Glaucoma Symptoms: </b>\r\n<br/>\r\n•No symptoms appear in the early stages.<br/>\r\n•Gradual appearance of isolated blind spots in the lateral field of vision.<br/>\r\n•The lateral field of vision is also called peripheral vision.<br/>\r\n•Difficulty seeing objects in the field of central vision.<br/>\r\n•Severe headache.<br/>\r\n•severe eye pain.<br/>\r\n•Nausea or vomiting.<br/>\r\n•Blurred vision.<br/>\r\n•Seeing colored halos or rings around lights.<br/>\r\n•Eye redness.<br/>\r\n•Glaucoma with normal eye pressure.<br/>\r\n•No symptoms appear in the early stages.<br/>\r\n•Blurred vision appears gradually.<br/>\r\n•In the later stages, loss of side vision.<br/>\r\n\r\n'),
(11, 'Glaucoma Risk factors |glaucoma risk factors |GLAUCOMA RISK FACTORS |glaucoma risk factor |GLAUCOMA RISK FACTOR |Glaucoma Risk factor', '<b> Glaucoma Risk factors: </b>\r\n<br/>\r\nGlaucoma can damage your vision before you notice any symptoms. So, be aware of the following risk factors:<br/>\r\n•Increased intraocular pressure.<br/>\r\n•Over the age of 55 years.<br/>\r\n•Black, Asian or Hispanic descent.<br/>\r\n•Presence of previous glaucoma injuries in the family.<br/>\r\n•Infection with certain diseases such as diabetes, migraines, high blood pressure, and sickle cell anemia.<br/>\r\n•Thinning of the cornea from the middle.<br/>\r\n•severe nearsightedness or farsightedness.<br/>\r\n•Injury to the eye and some types of eye operations.<br/>\r\n•Taking corticosteroids, especially eye drops, for a long time.<br/>\r\n'),
(12, 'glaucoma diagnosis |GLAUCOMA DIAGNOSIS| Glaucoma Diagnosis', '<b> Glaucoma Diagnosis: </b>\r\n<br/>\r\n•Damage to the optic nerve and deterioration of its condition.<br/>\r\n•Blind spots in the field of vision due to high intraocular pressure.<br/>\r\n•Prominence of the iris.<br/>\r\n•Increased eye pressure.<br/>\r\n\r\n'),
(13, 'Glaucoma Treatment |glaucoma treatment |GLAUCOMA TREATMENT', '<b> Glaucoma Treatment: </b>\r\n<br/>\r\nThe damage caused by glaucoma can\'t be \r\nreversed. But treatment and regular checkups can help slow or prevent vision loss, especially if you catch the disease in its early stages.<br/>\r\n\r\nGlaucoma is treated by lowering intraocular pressure. Treatment options include prescription eye drops, oral medicines, laser treatment, surgery or a combination of approaches.<br/>'),
(14, 'GLAUCOMA PROTECTION |Glaucoma Protection |glaucoma protection', '<b> Glaucoma Protection: </b>\r\n<br/>\r\n•Examination of eyes regularly.<br/>\r\n•Wear eye protection.<br/>\r\n•Use prescribed eye drops regularly.<br/>\r\n'),
(15, 'DRY EYE | dry eye |Dry Eye|3', 'Please choose what you want.</br>\r\n<b>Dry Eye Symptoms</b> <br/>\r\n<b>Dry Eye Risk factors</b> <br/>\r\n<b>Dry Eye Diagnosis</b> <br/>\r\n<b>Dry Eye Treatment</b> <br/>\r\n<b>Dry Eye Protection</b> <br/>'),
(16, 'dry eye symptoms |Dry Eye Symptoms |DRY EYE SYMPTOMS\r\n', '<b>Dry Eye Symptoms</b> <br/>\r\n•Stinging, burning or roughness in the eyes.<br/>\r\n•Sticky pus in or around the eyes.<br/>\r\n•sensitivity to light.<br/>\r\n•Eye redness.<br/>\r\n•Sensation of having something in the eyes.<br/>\r\n•Difficulty wearing contact lenses.<br/>\r\n•Difficulty driving at night.<br/>\r\n•Watery eyes, The body\'s response to irritation is dry eyes.<br/>\r\n•Cloudy vision and eye fatigue.<br/>\r\n'),
(17, 'Dry Eye Risk factors |dry eye risk factors |DRY EYE RISK FACTORS |dry eye risk factor |DRY EYE RISK FACTOR |Dry Eye Risk factor', '<b>Dry Eye Risk factors</b> <br/>\r\n•getting older.<br/>\r\n•Follow a diet that is low in vitamin A.<br/>\r\n•Wear contact lenses.<br/>\r\n•Performing eye refractive surgery.<br/>\r\n'),
(18, 'dry eye diagnosis |DRY EYE DIAGNOSIS| Dry Eye Diagnosis', '<b>Dry Eye Diagnosis</b> <br/>\r\n•Lacrimal membrane defect.<br/>\r\n•Decreased secretion of tears.<br/>\r\n•Advance in age.<br/>\r\n•Decreased sensitivity of the village nerve caused by the use of contact lenses.<br/>\r\n•Nerve damage or laser eye surgery.<br/>\r\n'),
(19, 'Dry Eye Treatment |dry eye treatment |DRY EYE TREATMENT', '<b>Dry Eye Treatment</b> <br/>\r\n1.clean your eyelids every day.<br/>\r\n2.take breaks to rest your eyes when using a computer screen.<br/>\r\n3.make sure your computer screen is just below eye level.<br/>\r\n4.use a humidifier to stop the air getting dry.<br/>\r\n5.if you wear contact lenses, take them out and wear glasses to rest your eyes.<br/>'),
(20, 'DRY EYE PROTECTION |Dry Eye Protection |dry eye protection', '<b>Dry Eye Protection</b> <br/>\r\n•Avoid directing the air into your eyes.<br/>\r\n•Wear sunglasses.<br/>\r\n•Put the computer screen in a position lower than the level of your eyes.<br/>\r\n•Quit smoking if you smoke.<br/>\r\n•Use of artificial tears.<br/>\r\n'),
(21, 'Keratoconus| keratoconus |KERATOCONUS|4', 'Please choose what you want.</br>\r\n<b>Keratoconus Symptoms</b> <br/>\r\n<b>Keratoconus Diagnosis</b> <br/>\r\n<b>Keratoconus Treatment</b> <br/>\r\n<b>Keratoconus Protection</b> <br/>'),
(22, 'keratoconus symptoms |Keratoconus Symptoms |KERATOCONUS SYMPTOMS\r\n', '<b>Keratoconus Symptoms</b> <br/>\r\n•Weakness of the cornea, which leads to its emergence.<br/>\r\n•Frequent rubbing of the eye affects the integrity of the cornea.<br/>\r\n•Rapid deterioration of vision that may lead to loss.<br/>\r\n•Low vision and the need to change glasses continuously in the early stages.<br/>\r\n•Inability to tolerate light.<br/>\r\n'),
(23, 'keratoconus diagnosis |KERATOCONUS DIAGNOSIS| Keratoconus Diagnosis', '<b>Keratoconus Diagnosis</b> <br/>\r\n•Examine the refraction of light to determine the appropriate lens size for vision correction.<br/>\r\n•Measurement of the curvature of the cornea.<br/>\r\n•Imaging of the cornea to identify the affected areas.<br/>\r\n•Measurement of corneal thickness.<br/>\r\n'),
(24, 'Keratoconus Treatment |keratoconus treatment |KERATOCONUS TREATMENT', '<b>Keratoconus Treatment</b> <br/>\r\n•In the early stages, the focus is on correcting vision by using medical glasses or soft contact lenses.<br/>\r\n•When the condition of vision worsens, oxygen permeable contact lenses (hard lenses) are used.<br/>\r\n•In the advanced stages, surgical operations (corneal transplantation) are performed.<br/>\r\n'),
(25, 'KERATOCONUS PROTECTION |Keratoconus Protection |keratoconus protection', '<b>Keratoconus Protection</b> <br/>\r\n•Regular eye examination.<br/>\r\n•Avoid rubbing the eye.<br/>\r\n•Follow the doctor\'s instructions and inform him of the development of the situation as soon as possible.<br/>\r\n•Avoid using any medicine not prescribed by the doctor.<br/>\r\n•Pay attention to eye hygiene.<br/>\r\n•Avoid anything that irritates the eyes.<br/>\r\n•Protect eyes while swimming and playing sports.<br/>\r\n'),
(26, 'Keratitis | keratitis| KERATITIS|5', 'Please choose what you want.</br>\r\n<b>Keratitis Symptoms</b> <br/>\r\n<b>Keratitis Risk factors</b> <br/>\r\n<b>Keratitis Diagnosis</b> <br/>\r\n<b>Keratitis Treatment</b> <br/>\r\n<b>Keratitis Protection</b> <br/>'),
(27, 'keratitis symptoms |Keratitis Symptoms |KERATITIS SYMPTOMS\r\n', '<b>Keratitis Symptoms</b> <br/>\r\n•eye redness.<br/>\r\n•eye pain.<br/>\r\n•Excessive tearing or other secretions from the eyes.<br/>\r\n•Difficulty opening the eyelid due to pain or irritation.<br/>\r\n•Blurred vision.<br/>\r\n•decreased vision.<br/>\r\n•Sensitivity to light, also called photophobia.<br/>\r\n•Feeling as if there is something in your eye.<br/>\r\n'),
(28, 'Keratitis Risk factors |keratitis risk factors |KERATITIS RISK FACTORS |keratitis risk factor |KERATITIS RISK FACTOR |Keratitis Risk factor', '<b>Keratitis Risk factors</b> <br/>\r\n•contact lenses.<br/>\r\n•Low immunity.<br/>\r\n•Corticosteroids.<br/>\r\n•Injury to the eye.<br/>\r\n\r\n'),
(29, 'keratitis diagnosis |KERATITIS DIAGNOSIS| Keratitis Diagnosis', '<b>Keratitis Diagnosis</b> <br/>\r\n•Exposure to wounds in the eye.<br/>\r\n•Bacteria, fungi or parasites.<br/>\r\n•viruses.<br/>\r\n•Contaminated water.<br/>'),
(30, 'Keratitis Treatment |keratitis treatment |KERATITIS TREATMENT', '<b>Keratitis Treatment</b> <br/>\r\nTreatment of noninfectious keratitis varies depending on the severity. For example, with mild discomfort from a corneal scratch, artificial tear drops may be the only treatment. However, if keratitis is causing significant tearing and pain, topical eye medications may be necessary.'),
(31, 'KERATITIS PROTECTION |Keratitis Protection |keratitis protection', '<b>Keratitis Protection</b> <br/>\r\n•Care of contact lenses.<br/>\r\n•Prevention of virus outbreaks.<br/>\r\n'),
(32, 'Retinal Detachment | retinal detachment|6 |RETINAL DETACHMENT', 'Please choose what you want.</br>\r\n<b>Retinal Detachment Symptoms</b> <br/>\r\n<b>Retinal Detachment Risk factors</b> <br/>\r\n<b>Retinal Detachment Diagnosis</b> <br/>\r\n<b>Retinal Detachment Treatment</b> <br/>\r\n<b>Retinal Detachment Protection</b> <br/>'),
(33, 'retinal detachment symptoms |Retinal Detachment Symptoms |RETINAL DETACHMENT SYMPTOMS\r\n', '<b>Retinal Detachment Symptoms</b> <br/>\r\n•The sudden appearance of floaters, which are tiny objects that appear to float in your field of vision.<br/>\r\n•Flashes of light in one or both eyes (photopsia).<br/>\r\n•Blurred vision.<br/>\r\n•Side (peripheral) vision gradually decreases.<br/>\r\n•The appearance of a curtain-like shadow in the field of vision.<br/>\r\n'),
(34, 'Retinal Detachment Risk factors |retinal detachment risk factors |RETINAL DETACHMENT RISK FACTORS |retinal detachment risk factor |RETINAL DETACHMENT RISK FACTOR |Retinal Detachment Risk factor', '<b>Retinal Detachment Risk factors</b> <br/>\r\n•Aging.<br/>\r\n•Excessive nearsightedness (myopia).<br/>\r\n•Previous eye surgery, such as cataract removal.<br/>\r\n•Previous acute eye injury.<br/>\r\n•Other previous diseases or disorders of the eye.<br/>\r\n'),
(35, 'retinal detachment diagnosis |RETINAL DETACHMENT DIAGNOSIS| Retinal Detachment Diagnosis', '<b>Retinal Detachment Diagnosis</b> <br/>\r\n•A hole or tear in the retina.<br/>\r\n•Detachment of the tissue that lies below the retina.<br/>\r\n•Advance in age.<br/>\r\n'),
(36, 'Retinal Detachment Treatment |retinal detachment treatment |RETINAL DETACHMENT TREATMENT', '<b>Retinal Detachment Treatment</b> <br/>\r\n•laser surgery.<br/>\r\n•Cryosynthesis (cryofixation of the retina).<br/>\r\n'),
(37, 'RETINAL DETACHMENT PROTECTION |Retinal Detachment Protection |retinal detachment protection', '<b>Retinal Detachment Protection</b> <br/>\r\nIf you experience any symptoms of retinal detachment, go to your eye doctor or the emergency room right away. Early treatment can help prevent permanent vision loss.<br/>\r\nIt’s also important to get comprehensive dilated eye exams regularly. A dilated eye exam can help your eye doctor find a small retinal tear or detachment early, before it starts to affect your vision.<br/>\r\n'),
(38, 'Disease Prediction |disease prediction', 'Please enter the symptoms that you feel in order to show you the result of the diagnosis.'),
(39, 'Gradual visual impairment without pain|\r\nFrequent change of glasses or contact lenses|\r\n The color of the lens of the eye gradually changes to white or brown|\r\n Blurry vision |fog|\r\n \r\n Difficulty seeing at night|\r\n Seeing halos around light sources|\r\n Yellowing of colors|\r\n Difficulty reading and distinguishing faces\r\n', 'There is a possibility that you have <b>Cataract</b> please see an ophthalmologist'),
(40, 'Gradual appearance of isolated blind spots in the lateral field of vision|\r\nDifficulty seeing objects in the field of central vision|\r\nSevere headache|\r\nsevere eye pain|\r\nNausea or vomiting|\r\nBlurred vision|\r\nSeeing colored halos or rings around lights|\r\n\r\nGlaucoma with normal eye pressure|\r\n\r\nBlurred vision appears gradually|\r\nloss of side vision|\r\n', 'There is a possibility that you have <b>Glaucoma</b> please see an ophthalmologist'),
(41, 'Stinging, burning or roughness in the eyes|\r\nSticky pus in or around the eyes|\r\n\r\n\r\nSensation of having something in the eyes|\r\nDifficulty wearing contact lenses|\r\nDifficulty driving at night|\r\nWatery eyes|\r\nCloudy vision and eye fatigue|\r\n', 'There is a possibility that you have <b>Dry Eye</b> please see an ophthalmologist'),
(42, 'Weakness of the cornea|\r\nFrequent rubbing of the eye|\r\nRapid deterioration of vision|\r\nLow vision and the need to change glasses continuously|\r\n\r\n', 'There is a possibility that you have <b>Keratoconus</b> please see an ophthalmologist'),
(43, '\r\neye pain|\r\nExcessive tearing or other secretions from the eyes|\r\nDifficulty opening the eyelid due to pain or irritation|\r\nBlurred vision|\r\ndecreased vision|\r\n\r\nFeeling as if there is something in your eye|\r\n', 'There is a possibility that you have <b>Keratitis</b> please see an ophthalmologist'),
(44, ' The sudden appearance of floaters on your eye|\r\nFlashes of light|\r\nBlurred vision|\r\nSide vision gradually decreases|\r\nThe appearance of shadow in the field of vision\r\n', 'There is a possibility that you have <b>Retinal Detachment</b> please see an ophthalmologist'),
(45, 'sensitivity to light|\r\nEye redness|\r\n', 'There is a possibility that you have <b>Dry Eye or Glaucoma or Cataract or Keratoconus or Keratitis </b> please see an ophthalmologist'),
(46, 'english |English |ENGLISH |الانجليزيه |انجليزيه', 'welcome in our eye diseases chatbot, please choose between <b>disease prediction or information<b/> about diseases'),
(47, 'arabic |Arabic | ARABIC | العربيه |عربيه', 'مرحبا بك في روبوت الدردشه الخاص بأمراض العيون من فضلك اختار بين <b> التنبؤ بالامراض او معلومات <b/>حول الامراض'),
(48, 'معلومات', 'الرجاء تحديد المرض الذي ترغب في معرفة المزيد عنه. <br/>\r\n1 • المياه البيضاء <br/>\r\n2 • الجلوكوما <br/>\r\n3 • جفاف العين <br/>\r\n4 • القرنية المخروطية. <br/>\r\n5 • التهاب القرنية <br/>\r\n6 • انفصال الشبكية. <br/>'),
(49, 'المياه البيضاء', 'الرجاء اختيار ما تريد. </br>\r\n<b> أعراض المياه البيضاء</ b> <br/>\r\n<b> عوامل خطر المياه البيضاء</ b> <br/>\r\n<b> تشخيص المياه البيضاء </ b> <br/>\r\n<b> علاج المياه البيضاء </ b> <br/>\r\n<b> حماية من المياه البيضاء </ b> <br/>'),
(50, 'أعراض المياه البيضاء | اعراض المياه البيضاء', 'أعراض المياه البيضاء: </ b>\r\n<br/>\r\n• ضعف البصر التدريجي دون ألم. <br/>\r\n• كثرة تغيير النظارات أو العدسات اللاصقة. <br/>\r\n• يتغير لون عدسة العين تدريجياً إلى الأبيض أو البني في الحالات المتقدمة. <br/>\r\n• رؤية ضبابية (ضباب). <br/>\r\n• الحساسية للأضواء. <br/>\r\n• صعوبة الرؤية في الليل. <br/>\r\n• رؤية هالات حول مصادر الضوء. <br/>\r\n• اصفرار الألوان <br/>\r\n• صعوبة القراءة والتمييز بين الوجوه. <br/>'),
(51, 'عوامل خطر المياه البيضاء', '<b> عوامل خطر المياه البيضاء </ b> <br/>\r\n• تقدم في العمر <br/>\r\n• التعرض لأشعة الشمس (الأشعة فوق البنفسجية). <br/>\r\n• التعرض لضربة أو إصابة بالعين. <br/>\r\n• الإصابة بمرض السكري. <br/>\r\n• ارتفاع ضغط الدم. <br/>\r\n• بعض الأدوية وأهمها الكورتيزون. <br/>\r\n• التعرض المسبق للعيون العمياء. <br/>\r\n• التدخين. <br/>'),
(52, 'تشخيص المياه البيضاء', '<b> تشخيص المياه البيضاء: </ b> </br>\r\n1. الفحص السريري <br/>\r\n2. التاريخ الطبي. <br/>\r\nالخضوع لبعض الاختبارات <br/>\r\n1. قياس حدة البصر. <br/>\r\n2. تقييم العدسة وشبكية العين. <br/>\r\n3. قياس الضغط داخل العين. <br/>\r\n4. تنظير قاع العين <br/>\r\n5. مشاهدة انعكاس الضوء الأحمر. حيث أن غيابه يعني وجود عتامة. <br/>'),
(53, 'علاج المياه البيضاء', '<b> علاج الساد </ b> </br>\r\nالعلاج الوحيد لها هو التدخل الجراحي. <br/>\r\n   من أهم التدخلات الجراحية إزالة العدسة المصابة بالساد واستبدالها بزرع عدسة أخرى جديدة تدوم مدى الحياة. هذه العملية لها طرق مختلفة في حالات مختلفة.'),
(54, 'حماية من المياه البيضاء', '<b> علاج المياه البيضاء </ b> </br>\r\n• إجراء فحوصات عين منتظمة. <br/>\r\n• الإقلاع عن التدخين. <br/>\r\n• اتبع خطة علاج المشاكل الصحية مثل: السكري ، وغيرها. <br/>\r\n• اختر نظامًا غذائيًا صحيًا يحتوي على الفيتامينات ومضادات الأكسدة. <br/>\r\n• ارتداء النظارات الشمسية التي تحجب الأشعة فوق البنفسجية.'),
(55, 'الجلوكوما', 'الرجاء اختيار ما تريد. </br>\r\n<b> أعراض الجلوكوما </ b> <br/>\r\n<b> عوامل خطر الجلوكوما </ b> <br/>\r\n<b> تشخيص الجلوكوما </ b> <br/>\r\n<b> علاج الجلوكوما </ b> <br/>\r\n<b> الحماية من الجلوكوما </ b> <br/>'),
(56, 'أعراض الجلوكوما|اعراض الجلوكوما', 'أعراض الجلوكوما: </ b>\r\n<br/>\r\n• لا توجد أعراض تظهر في المراحل المبكرة. <br/>\r\n• الظهور التدريجي للبقع العمياء المعزولة في مجال الرؤية الجانبي. <br/>\r\n• مجال الرؤية الجانبي يسمى أيضا الرؤية المحيطية. <br/>\r\n• صعوبة رؤية الأشياء في مجال الرؤية المركزية. <br/>\r\n• صداع شديد. <br/>\r\n• ألم شديد بالعين. <br/>\r\n• غثيان أو قيء. <br/>\r\n• رؤية مشوشة. <br/>\r\n• رؤية هالات ملونة أو حلقات حول الأضواء. <br/>\r\n• احمرار العين. <br/>\r\n• الجلوكوما مع ضغط العين الطبيعي. <br/>\r\n• لا توجد أعراض تظهر في المراحل المبكرة. <br/>\r\n• عدم وضوح الرؤية يظهر تدريجياً. <br/>\r\n• في المراحل اللاحقة فقدان الرؤية الجانبية. <br/>'),
(57, 'عوامل خطر الجلوكوما', '<b> عوامل خطر الجلوكوما: </ b>\r\n<br/>\r\nيمكن أن يضر الجلوكوما بصرك قبل أن تلاحظ أي أعراض. لذا ، كن على دراية بعوامل الخطر التالية: <br/>\r\n• زيادة ضغط العين. <br/>\r\n• يزيد عمره عن 55 سنة. <br/>\r\n• من أصل أسود أو آسيوي أو من أصل إسباني. <br/>\r\n• وجود إصابات سابقة بالزرق في الأسرة. <br/>\r\n• الإصابة بأمراض معينة مثل السكري والصداع النصفي وارتفاع ضغط الدم وفقر الدم المنجلي. <br/>\r\n• ترقق القرنية من الوسط. <br/>\r\n• قصر النظر الشديد أو طول النظر. <br/>\r\n• إصابة العين وبعض أنواع عمليات العيون. <br/>\r\n• تناول الكورتيكوستيرويدات ، وخاصة قطرات العين ، لفترة طويلة. <br/>'),
(58, 'تشخيص الجلوكوما', '<b> تشخيص الجلوكوما: </ b>\r\n<br/>\r\n• تضرر العصب البصري وتدهور حالته. <br/>\r\n• نقاط عمياء في مجال الرؤية نتيجة لارتفاع ضغط العين. <br/>\r\n• بروز القزحية. <br/>\r\n• زيادة ضغط العين. <br/>'),
(59, 'علاج الجلوكوما', '<b> علاج الجلوكوما: </ b>\r\n<br/>\r\nلا يمكن أن يكون الضرر الناجم عن الجلوكوما\r\nعكس. لكن العلاج والفحوصات المنتظمة يمكن أن تساعد في إبطاء أو منع فقدان البصر ، خاصة إذا أصبت بالمرض في مراحله المبكرة. <br/>\r\n\r\nيتم علاج الجلوكوما عن طريق خفض ضغط العين. تشمل خيارات العلاج قطرات العين التي تُصرف بوصفة طبية أو الأدوية الفموية أو العلاج بالليزر أو الجراحة أو مجموعة من الأساليب. <br/>'),
(60, 'الحماية من الجلوكوما', '<b> الحماية من الجلوكوما: </ b>\r\n<br/>\r\n• فحص العيون بانتظام. <br/>\r\n• ارتداء واقي للعينين <br/>\r\n• استخدم قطرات العين الموصوفة بانتظام. <br/>'),
(61, 'جفاف العين', 'الرجاء اختيار ما تريد. </br>\r\n<b> أعراض جفاف العين </ b> <br/>\r\n<b> عوامل خطر جفاف العين </ b> <br/>\r\n<b> تشخيص جفاف العين </ b> <br/>\r\n<b> علاج جفاف العين </ b> <br/>\r\n<b> حماية جفاف العين </ b> <br/>'),
(62, 'أعراض جفاف العين |اعراض جفاف العين', '<b> أعراض جفاف العين </ b> <br/>\r\n• لاذع أو حرقان أو خشونة في العينين. <br/>\r\n• صديد لزج داخل أو حول العينين. <br/>\r\n• الحساسية للضوء. <br/>\r\n• احمرار العين. <br/>\r\n• الإحساس بوجود شيء في العيون. <br/>\r\n• صعوبة ارتداء العدسات اللاصقة. <br/>\r\n• صعوبة القيادة ليلاً. <br/>\r\n• عيون دامعة ، استجابة الجسم للتهيج هي جفاف العين. <br/>\r\n• رؤية ضبابية وإرهاق في العين. <br/>'),
(63, 'عوامل خطر جفاف العين', '<b> عوامل خطر جفاف العين </ b> <br/>\r\n• التقدم في السن <br/>\r\n• اتبع نظامًا غذائيًا يحتوي على نسبة منخفضة من فيتامين أ. <br/>\r\n• ارتداء العدسات اللاصقة. <br/>\r\n• إجراء جراحة انكسار العين <br/>'),
(64, 'تشخيص جفاف العين', '<b> تشخيص جفاف العين </ b> <br/>\r\n• عيب الغشاء الدمعي. <br/>\r\n• قلة إفراز الدموع. <br/>\r\n• التقدم في العمر <br/>\r\n• انخفاض حساسية العصب القروي نتيجة استخدام العدسات اللاصقة. <br/>\r\n• تلف الأعصاب أو جراحة العيون بالليزر. <br/>'),
(65, 'علاج جفاف العين', '<b> علاج جفاف العين </ b> <br/>\r\n1. نظف جفونك كل يوم. <br/>\r\n2. خذ فترات راحة لإراحة عينيك عند استخدام شاشة الكمبيوتر. <br/>\r\n3. تأكد من أن شاشة الكمبيوتر أقل بقليل من مستوى العين. <br/>\r\n4.استخدم المرطب لمنع جفاف الهواء. <br/>\r\n5. إذا كنت ترتدي العدسات اللاصقة ، فقم بإخراجها وارتداء النظارات لإراحة عينيك. <br/>'),
(66, 'حماية جفاف العين', '<b> حماية جفاف العين </ b> <br/>\r\n• تجنب توجيه الهواء إلى عينيك. <br/>\r\n• ارتداء النظارات الشمسية. <br/>\r\n• ضع شاشة الكمبيوتر في موضع أدنى من مستوى عينيك. <br/>\r\n• الإقلاع عن التدخين إذا كنت تدخن. <br/>\r\n• استخدام القطرات. <br/>'),
(67, 'القرنية المخروطية', 'الرجاء اختيار ما تريد. </br>\r\n<b> أعراض القرنية المخروطية </ b> <br/>\r\n<b> تشخيص القرنية المخروطية </ b> <br/>\r\n<b> علاج القرنية المخروطية </ b> <br/>\r\n<b> حماية القرنية المخروطية </ b> <br/>'),
(68, 'أعراض القرنية المخروطية | اعراض القرنية المخروطية', '<b> أعراض القرنية المخروطية </ b> <br/>\r\n• ضعف القرنية مما يؤدي إلى ظهورها. <br/>\r\n• كثرة فرك العين يؤثر على سلامة القرنية. <br/>\r\n• التدهور السريع للرؤية الذي قد يؤدي إلى فقدانه. <br/>\r\n• ضعف البصر والحاجة إلى تغيير النظارات بشكل مستمر في المراحل المبكرة. <br/>\r\n• عدم القدرة على تحمل الضوء. <br/>'),
(69, 'تشخيص القرنية المخروطية', '<b> تشخيص القرنية المخروطية </ b> <br/>\r\n• فحص انكسار الضوء لتحديد حجم العدسة المناسب لتصحيح الرؤية. <br/>\r\n• قياس انحناء القرنية. <br/>\r\n• تصوير القرنية للتعرف على المناطق المصابة. <br/>\r\n• قياس سمك القرنية. <br/>'),
(70, 'علاج القرنية المخروطية', '<b> علاج القرنية المخروطية </ b> <br/>\r\n• في المراحل المبكرة ، ينصب التركيز على تصحيح الرؤية باستخدام النظارات الطبية أو العدسات اللاصقة اللينة. <br/>\r\n• عندما تسوء حالة الرؤية ، يتم استخدام العدسات اللاصقة المنفذة للأكسجين (العدسات الصلبة). <br/>\r\n• في المراحل المتقدمة يتم إجراء العمليات الجراحية (زراعة القرنية). <br/>'),
(71, 'حماية القرنية المخروطية', '<b> حماية القرنية المخروطية </ b> <br/>\r\n• فحص العين الدوري. <br/>\r\n• تجنب فرك العين. <br/>\r\n• اتبع تعليمات الطبيب وأبلغه بتطور الوضع في أسرع وقت ممكن. <br/>\r\n• تجنب استخدام أي دواء لم يصفه الطبيب. <br/>\r\n• انتبه لنظافة العين. <br/>\r\n• تجنب كل ما يزعج العينين. <br/>\r\n• حماية العيون أثناء السباحة وممارسة الرياضة. <br/>'),
(72, 'التهاب القرنية', 'الرجاء اختيار ما تريد. </br>\r\n<b>أعراض التهاب القرنية </ b> <br/>\r\n<b> عوامل خطر التهاب القرنية </ b> <br/>\r\n<b> تشخيص التهاب القرنية </ b> <br/>\r\n<b> علاج التهاب القرنية </ b> <br/>\r\n<b> حماية القرنية </ b> <br/>'),
(73, 'أعراض التهاب القرنية | اعراض التهاب القرنية', 'أعراض التهاب القرنية </ b> <br/>\r\n• احمرار العين. <br/>\r\n• ألم في العين. <br/>\r\n• تمزق مفرط أو إفرازات أخرى من العين. <br/>\r\n• صعوبة فتح الجفن بسبب الألم أو التهيج. <br/>\r\n• رؤية مشوشة. <br/>\r\n• ضعف الرؤية. <br/>\r\n• الحساسية للضوء ، وتسمى أيضًا رهاب الضوء. <br/>\r\n• الشعور وكأن هناك شيء ما في عينك. <br/>'),
(74, 'عوامل خطر التهاب القرنية', '<b> عوامل خطر التهاب القرنية </ b> <br/>\r\n• العدسات اللاصقة. <br/>\r\n• مناعة منخفضة. <br/>\r\n• الستيرويدات القشرية. <br/>\r\n• إصابة في العين. <br/>'),
(75, 'تشخيص التهاب القرنية', '<b> تشخيص التهاب القرنية </ b> <br/>\r\n• التعرض لجروح في العين. <br/>\r\n• البكتيريا أو الفطريات أو الطفيليات. <br/>\r\n• الفيروسات. <br/>\r\n• المياه الملوثة <br/>'),
(76, 'علاج التهاب القرنية', '<b> علاج التهاب القرنية </ b> <br/>\r\nيختلف علاج التهاب القرنية غير المعدي تبعًا لشدته. على سبيل المثال ، مع الشعور بعدم الراحة من خدش القرنية ، قد تكون قطرات الدموع الاصطناعية هي العلاج الوحيد. ومع ذلك ، إذا تسبب التهاب القرنية في حدوث تمزق وألم شديد ، فقد تكون الأدوية الموضعية للعين ضرورية.'),
(77, 'حماية التهاب القرنية', '<b> حماية القرنية </ b> <br/>\r\n• العناية بالعدسات اللاصقة. <br/>\r\n• منع تفشي الفيروسات. <br/>'),
(78, 'انفصال الشبكية', 'الرجاء اختيار ما تريد. </br>\r\n<b> أعراض انفصال الشبكية </ b> <br/>\r\n<b> عوامل خطر الإصابة بانفصال الشبكية </ b> <br/>\r\n<b> تشخيص انفصال الشبكية </ b> <br/>\r\n<b> علاج انفصال الشبكية </ b> <br/>\r\n<b> حماية انفصال الشبكية </ b> <br/>'),
(79, 'أعراض انفصال الشبكية | اعراض انفصال الشبكية', '<b> أعراض انفصال الشبكية </ b> <br/>\r\n• الظهور المفاجئ للعوائم ، وهي أجسام صغيرة تبدو وكأنها تطفو في مجال رؤيتك. <br/>\r\n• ومضات من الضوء في إحدى العينين أو كلتيهما (صور ضوئية). <br/>\r\n• رؤية مشوشة. <br/>\r\n• الرؤية الجانبية (المحيطية) تنخفض تدريجياً. <br/>\r\n• ظهور الظل كالستارة في مجال الرؤية. <br/>'),
(80, 'عوامل خطر الإصابة بانفصال الشبكية', '<b> عوامل خطر الإصابة بانفصال الشبكية </ b> <br/>\r\n• الشيخوخة. <br/>\r\n• قصر النظر المفرط (قصر النظر). <br/>\r\n• جراحة العيون السابقة ، مثل إزالة المياه البيضاء. <br/>\r\n• إصابة العين الحادة السابقة. <br/>\r\n• أمراض أو اضطرابات العين السابقة الأخرى. <br/>'),
(81, 'تشخيص انفصال الشبكية', '<b> تشخيص انفصال الشبكية </ b> <br/>\r\n• ثقب أو تمزق في الشبكية. <br/>\r\n• انفصال النسيج الذي يقع تحت الشبكية. <br/>\r\n• التقدم في العمر <br/>'),
(82, 'علاج انفصال الشبكية', '<b> علاج انفصال الشبكية </ b> <br/>\r\n• جراحة الليزر. <br/>\r\n• التركيب بالتبريد (تثبيت الشبكية بالتبريد). <br/>'),
(83, 'حماية انفصال الشبكية', '<b> حماية انفصال الشبكية </ b> <br/>\r\nإذا واجهت أي أعراض لانفصال الشبكية ، فانتقل إلى طبيب العيون أو غرفة الطوارئ على الفور. يمكن أن يساعد العلاج المبكر في منع فقدان البصر الدائم. <br/>\r\nمن المهم أيضًا إجراء فحوصات شاملة للعين الموسعة بانتظام. يمكن أن يساعد فحص العين التوسعي طبيب العيون في العثور على تمزق أو انفصال صغير في الشبكية مبكرًا ، قبل أن يبدأ في التأثير على رؤيتك. <br/>'),
(84, 'التنبؤ بالامراض | تنبؤ بالامراض', 'يرجى إدخال الأعراض التي تشعر بها لتظهر لك نتيجة التشخيص.'),
(85, 'ضعف بصري تدريجي بدون ألم |\r\nكثرة تغيير النظارات أو العدسات اللاصقة |\r\n  يتغير لون عدسة العين تدريجياً إلى الأبيض أو البني |\r\n  رؤية ضبابية | ضباب |\r\n \r\n  صعوبة الرؤية بالليل |\r\n  رؤية هالات حول مصادر الضوء |\r\n  اصفرار الألوان |\r\n  صعوبة القراءة والتمييز بين الوجوه', 'هناك احتمال أن يكون لديك <b> المياه البيضاء </ b> ، يرجى مراجعة طبيب العيون'),
(86, 'الظهور التدريجي للبقع العمياء المعزولة في مجال الرؤية الجانبي |\r\nصعوبة رؤية الأشياء في مجال الرؤية المركزية |\r\nصداع شديد |\r\nألم شديد في العين |\r\nغثيان أو قيء |\r\nرؤية مشوشة |\r\nرؤية هالات أو حلقات ملونة حول الأضواء |\r\n\r\nالجلوكوما مع ضغط العين الطبيعي |\r\n\r\nرؤية غير واضحة تظهر تدريجياً |\r\nفقدان الرؤية الجانبية |', 'من المحتمل أن يكون لديك <b> الجلوكوما </ b> ، يرجى مراجعة طبيب العيون'),
(87, 'لاذع أو حرقة أو خشونة بالعينين |\r\nصديد لزج داخل أو حول العينين |\r\n\r\n\r\nالإحساس بوجود شيء ما في العيون |\r\nصعوبة ارتداء العدسات اللاصقة |\r\nصعوبة القيادة ليلاً |\r\nعيون دامعة |\r\nرؤية ضبابية وتعب في العين |', 'من المحتمل أن يكون لديك <b> جفاف العين </ b> ، يرجى مراجعة طبيب العيون'),
(88, 'ضعف القرنية |\r\nكثرة فرك العين |\r\nالتدهور السريع للرؤية |\r\nضعف البصر وضرورة تغيير النظارات بشكل مستمر |', 'من المحتمل أن يكون لديك <b> القرنية المخروطية </ b> ، يرجى مراجعة طبيب العيون'),
(89, 'ألم العين |\r\nتمزق مفرط أو إفرازات أخرى من العين |\r\nصعوبة فتح الجفن بسبب الألم أو التهيج |\r\nرؤية مشوشة |\r\nانخفاض الرؤية |\r\n\r\nالشعور كما لو أن هناك شيئًا ما في عينك |', 'هناك احتمال أن يكون لديك <b> التهاب القرنية </ b> يرجى مراجعة طبيب العيون'),
(90, 'الظهور المفاجئ للعوائم على عينك |\r\nومضات من الضوء |\r\nرؤية مشوشة |\r\nتقلص الرؤية الجانبية تدريجياً |\r\nظهور الظل في مجال الرؤية', 'من المحتمل أن يكون لديك <b> انفصال الشبكية </ b> ، يرجى مراجعة طبيب العيون'),
(91, 'حساسية للضوء |\r\nاحمرار العين |', 'هناك احتمال أن يكون لديك <b> جفاف العين أو الجلوكوما أو إعتام عدسة العين أو القرنية المخروطية أو التهاب القرنية </ b> يرجى مراجعة طبيب العيون');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chatbot`
--
ALTER TABLE `chatbot`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `chatbot`
--
ALTER TABLE `chatbot`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=92;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
